import { SiteFooter } from "../../components/ui";

export const metadata = {
  title: "Privacy Policy — Cooperative CRM",
};

function Section({ title, children }) {
  return (
    <section className="mb-7">
      <h2 className="text-lg mb-2">{title}</h2>
      <div className="text-sm text-ink-soft leading-relaxed space-y-3">{children}</div>
    </section>
  );
}

export default function Privacy() {
  return (
    <div className="min-h-screen bg-paper font-sans">
      <div className="max-w-3xl mx-auto px-4 sm:px-8 py-12 sm:py-16">
        <a href="/" className="text-xs text-ink-soft hover:text-forest-dark">← Back to Cooperative CRM</a>
        <h1 className="text-3xl mt-4 mb-1">Privacy Policy</h1>
        <p className="text-xs text-ink-soft/70 mb-8">Last updated: August 2026</p>

        <div className="bg-white border border-line rounded-md p-6 sm:p-8">
          <Section title="1. Who this applies to">
            <p>
              Cooperative CRM is a member-management platform provided by Corporate Bundles for cooperative
              societies. This policy explains what information is collected through the platform, how it is
              used, and the rights available to cooperative members and administrators. It applies to every
              cooperative using Cooperative CRM, including NARP50+ Cooperative Society.
            </p>
          </Section>

          <Section title="2. Data controller and data processor">
            <p>
              Each cooperative using this platform (for example, NARP50+) is the <strong>data controller</strong> for
              its own members&rsquo; information — the cooperative decides what member data is recorded and why.
              Corporate Bundles operates Cooperative CRM as the <strong>data processor</strong>, storing and
              processing that data on the cooperative&rsquo;s behalf and under its instruction.
            </p>
          </Section>

          <Section title="3. Information we collect">
            <p>Depending on your role, the platform collects:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Account information</strong> — your email address, used to send a one-time sign-in link. We do not use passwords.</li>
              <li><strong>Member records</strong> — name, phone number, email address, join date, dues, and renewal date, entered by your cooperative&rsquo;s administrators.</li>
              <li><strong>Financial/product records</strong> — savings, loan, investment, or equity products and their transaction history, as recorded by your cooperative.</li>
              <li><strong>Payment information</strong> — when a cooperative subscribes to the platform, payment is handled entirely by Paystack. We never receive or store card numbers or bank account credentials.</li>
              <li><strong>Basic usage data</strong> — standard technical logs (timestamps, request metadata) generated by our hosting and database providers for security and reliability.</li>
            </ul>
          </Section>

          <Section title="4. How we use this information">
            <ul className="list-disc pl-5 space-y-1">
              <li>To provide the member ledger, savings/loan tracking, and member portal features your cooperative uses.</li>
              <li>To send transactional emails — sign-in links, portal invitations, and messages your cooperative chooses to send to its own members.</li>
              <li>To process and confirm subscription payments for the cooperative&rsquo;s account.</li>
              <li>To maintain the security, integrity, and availability of the platform.</li>
            </ul>
            <p>We do not sell member data, and we do not use it for advertising.</p>
          </Section>

          <Section title="5. Who we share information with">
            <p>Information is shared only with the service providers needed to run the platform, each acting as a processor on our behalf:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Supabase</strong> — database hosting and authentication.</li>
              <li><strong>Paystack</strong> — subscription payment processing for cooperatives.</li>
              <li><strong>Resend</strong> — delivery of transactional emails (sign-in links, portal invites, cooperative-sent messages).</li>
              <li><strong>Vercel</strong> — application hosting.</li>
            </ul>
            <p>
              Each cooperative&rsquo;s data is kept isolated from every other cooperative&rsquo;s data at the database
              level. Administrators and members of one cooperative cannot access another cooperative&rsquo;s records.
            </p>
          </Section>

          <Section title="6. Data retention">
            <p>
              Member and financial records are retained for as long as your cooperative maintains an active
              account, and for a reasonable period afterward to meet the cooperative&rsquo;s own record-keeping
              obligations. A cooperative may request deletion of its data at any time, subject to any legal or
              regulatory retention requirements that apply to cooperative societies.
            </p>
          </Section>

          <Section title="7. Your rights">
            <p>
              Under the Nigeria Data Protection Act (NDPA) 2023 and comparable data protection laws, you have
              the right to:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Request access to the personal data held about you.</li>
              <li>Request correction of inaccurate or incomplete data.</li>
              <li>Request deletion of your data, subject to your cooperative&rsquo;s own record-keeping requirements.</li>
              <li>Object to certain uses of your data.</li>
              <li>Be notified in the event of a data breach affecting your information.</li>
            </ul>
            <p>
              Since your cooperative is the data controller for its members&rsquo; information, these requests
              should generally be directed to your cooperative&rsquo;s administrators in the first instance. You
              can also reach us directly using the contact details below.
            </p>
          </Section>

          <Section title="8. Security">
            <p>
              Access to member data is restricted by role: cooperative administrators can manage their own
              cooperative&rsquo;s records, and individual members — where portal access has been enabled — can only
              view their own balances and transaction history, never another member&rsquo;s. Sign-in uses passwordless,
              one-time email links rather than stored passwords. Data is encrypted in transit.
            </p>
          </Section>

          <Section title="9. Children's data">
            <p>Cooperative CRM is intended for use by adult cooperative members and administrators, and is not directed at children.</p>
          </Section>

          <Section title="10. Changes to this policy">
            <p>We may update this policy from time to time as the platform evolves. Material changes will be reflected by updating the date at the top of this page.</p>
          </Section>

          <Section title="11. Contact">
            <p>
              Questions about this policy or your data can be directed to your cooperative&rsquo;s administrators,
              or to Corporate Bundles directly at{" "}
              <a href="mailto:info@corporatebundles.com" className="underline hover:text-forest-dark">info@corporatebundles.com</a>.
            </p>
          </Section>
        </div>
      </div>
      <SiteFooter className="max-w-3xl mx-auto" />
    </div>
  );
}
